### PR TITLE
Update GPL 3.0 license at package.json

### PR DESCRIPTION
**Pull request by orenyodfat**

### CODE REVIEW

**Comment by orenyodfat** [comment]
@dkent600 it is a public repo with many eyes on it,
Till other pr will be merged ,lets comment or approve this pr.

**Comment by dkent600** [comment]
Is this really that critical?

**Comment by orenyodfat** [comment]
It is not a major block stopper.
But it is needed as this repo is public repo having many eyes on it.
If the license of this repo is changed so the license on the npm package should be updated as well.

**Comment by dkent600** [comment]
Can this wait a few days until the docs PR that already contains this change is approved and merged?

**Comment by orenyodfat** [comment]
You could always override that with other pr.

**Pull request merged**
