### PR TITLE
Support poll interval to fetch from the graph

### PR DESCRIPTION
**Pull request by roienatan**
resolves: https://github.com/daostack/arc.js/issues/543

### CODE REVIEW

**Review by orenyodfat — CHANGES_REQUESTED** [review]
please add tests 
coveralls is decreased.

**Comment by orenyodfat** [comment]
does this enable to set the pollingInterval from the dapp(alchemy) ?

**Comment by roienatan** [comment]
> does this enable to set the pollingInterval from the dapp(alchemy) ?

Correct.

**Comment by orenyodfat** [comment]
-   add `polling` to `IApolloQueryOptions`  
-  `subscribe` and `polling` cannot be both true
- `pollingInterval` should have a default value of 15 seconds.
- `pollingInterval` default value will be used only if `pollingInterval` is not set or equal to zero.

**Comment by roienatan** [comment]
- [ ] if `pollInterval` is set but `polling` is `false` or `undefined` - throw an error

**Comment by roienatan** [comment]
Looks like there is some inconsistency in coveralls since the previous commit passed and in the current commit only a `.md` file was changed.

**Review by orenyodfat — APPROVED** [review]

**Pull request merged**
